apps/ride/urls.py
from apps.ride.views import (
    CompanyPanelView,
    DriverPanelView,
    EmergencyPanelView,
    FleetPanelView,
    ProgramingPanelView,
    RidePanelView,
    RideSearchView,
    RideDetailView,
)
from django.urls import path

urlpatterns = [
    path('', ProgramingPanelView.as_view(), name="home"),
    path('panel/programming', ProgramingPanelView.as_view(), name='programming'),
    path('panel/driver', DriverPanelView.as_view(), name='driver'),
    path('panel/fleet', FleetPanelView.as_view(), name='fleet'),
    path('panel/company', CompanyPanelView.as_view(), name='company'),
    path('panel/ride', RidePanelView.as_view(), name='ride'),
    path('panel/emergency', EmergencyPanelView.as_view(), name='emergency'),
    path('vale/', RideSearchView.as_view(), name='ride_search'),
    path('vale/<str:ride_code>', RideDetailView.as_view(), name='ride_detail'),
]

app_name = 'panel'

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("apps.ride.urls", namespace="panel")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # Swagger
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("api/mobile/", include("apps.ride.api.mobile.urls"), name='mobile'),
    path("api/fleet/", include("apps.ride.api.fleet.urls", namespace='api_fleet_panel'), name='api_fleet_panel'),
    path("api/company/", include("apps.ride.api.company.urls", namespace='api_company_panel'), name='api_company_panel'),
    path("api/driver/", include("apps.ride.api.driver.urls", namespace='api_driver_panel'), name='api_driver_panel'),
    path("api/ride/", include("apps.ride.api.ride.urls", namespace='api_ride_panel'), name='api_ride_panel'),
    path("api/programming/", include("apps.ride.api.programming.urls", namespace='api_programming_panel'), name='api_programming_panel'),
    path("api/emergency/", include("apps.ride.api.emergency.urls", namespace='api_emergency_panel'), name='api_emergency_panel'),
    # Django-rq
    path('django-rq/', include('django_rq.urls'))
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Grupo American SIRF{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/flatpickr.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/choices.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fixes.css' %}" rel="stylesheet">
    {% endblock %}

  </head>

  <body>

    {% if request.user.is_authenticated %}
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'panel:programming' %}">Grupo American SIRF</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'panel:fleet' %}">Flota</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'panel:company' %}">Compañías</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'panel:driver' %}">Conductores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'panel:programming' %}">Programación</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'panel:emergency' %}">Emergencia</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'panel:ride' %}">Viajes</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link">{{ request.user.first_name }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Cerrar Sesión</a>
              </li>
          </ul>
        </div>
      </nav>
    </div>
    {% endif %}

    <div class="container mt-2">
      {% block content %}
      {% endblock content %}
    </div> 

    {% block modal %}
    {% endblock modal %}
    <script src="{% static 'js/mdb.min.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/flatpickr.js' %}"></script>
    <script src="{% static 'js/ds.min.js' %}"></script>
    <script src="{% static 'js/choices.min.js' %}"></script>
    <script src="{% static 'js/constants.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>
 