apps/ride/api/emergency/urls.py
from django.urls import path

from .views import EmergencyListAPIView, EmergencyUpdateAPIView

urlpatterns = [
    path('', EmergencyListAPIView.as_view(), name='list'),
    path('', EmergencyUpdateAPIView.as_view(), name='update'),
    path('<int:pk>', EmergencyUpdateAPIView.as_view(), name='update'),
]

app_name = "api_emergency"

apps/ride/api/fleet/urls.py
from django.urls import path

from .views import (
    CarBrandListAPIView,
    CarCreateListAPIView,
    CarModelListAPIView,
    CarRetrieveUpdateDestroyAPIView,
)

urlpatterns = [
    path('', CarCreateListAPIView.as_view(), name='list_create'),
    path('', CarRetrieveUpdateDestroyAPIView.as_view(), name='retrieve_update_destroy'),
    path('<int:pk>', CarRetrieveUpdateDestroyAPIView.as_view(), name='retrieve_update_destroy'),
    path('brand', CarBrandListAPIView.as_view(), name='list_brand'),
    path('model', CarModelListAPIView.as_view(), name='list_Model'),
]

app_name = "api_programming"

apps/ride/api/programming/urls.py
from django.urls import path

from .views import (
    DriverProgrammingDataAPIView,
    ProgrammingCleanAPIView,
    ProgrammingDestroyAPIView,
    ProgrammingFinishAPIView,
    ProgrammingUpdateAPIView,
    ProgrammingUploadAPIView,
    RideCreateAPIView,
    ShiftAPIView,
)

urlpatterns = [
    path('file', ProgrammingUploadAPIView.as_view(), name='file'),
    path('shift/<int:id>', ShiftAPIView.as_view(), name='shift'),
    path('data/', DriverProgrammingDataAPIView.as_view(), name='driver_drift'),
    path('data/<int:id>', DriverProgrammingDataAPIView.as_view(), name='driver_drift'),
    path('ride', RideCreateAPIView.as_view(), name='ride'),
    path('remove/<int:pk>', ProgrammingDestroyAPIView.as_view(), name='programming_remove'),
    path('update/<int:pk>', ProgrammingUpdateAPIView.as_view(), name='programming_update'),
    path('clean/<int:id>', ProgrammingCleanAPIView.as_view(), name='programming_clean'),
    path('finish/<int:id>', ProgrammingFinishAPIView.as_view(), name='programming_finish'),
]

app_name = "api_programming"

apps/ride/api/ride/urls.py
from django.urls import path

from .views import (
    DriftCreateAPIView,
    DriftRetrieveUpdateDestroyAPIView,
    RateListAPIView,
    RideListAPIView,
    RideCreateAPIView,
    RideRetrieveUpdateDestroyAPIView,
)

urlpatterns = [
    path('', RideListAPIView.as_view(), name='list'),
    path('create', RideCreateAPIView.as_view(), name='create'),
    path('<int:pk>', RideRetrieveUpdateDestroyAPIView.as_view(), name='retrieve_update_update'),
    path('drift/', DriftCreateAPIView.as_view(), name='create_drift'),
    path('drift/<int:pk>', DriftRetrieveUpdateDestroyAPIView.as_view(), name='retrieve_update_destroy'),
    path('rate', RateListAPIView.as_view(), name='rate_list')
]

app_name = "api_ride"

apps/ride/urls.py
from apps.ride.views import (
    CompanyPanelView,
    DriverPanelView,
    EmergencyPanelView,
    FleetPanelView,
    ProgramingPanelView,
    RidePanelView,
    RideSearchView,
    RideDetailView,
)
from django.urls import path

urlpatterns = [
    path('', ProgramingPanelView.as_view(), name="home"),
    path('panel/programming', ProgramingPanelView.as_view(), name='programming'),
    path('panel/driver', DriverPanelView.as_view(), name='driver'),
    path('panel/fleet', FleetPanelView.as_view(), name='fleet'),
    path('panel/company', CompanyPanelView.as_view(), name='company'),
    path('panel/ride', RidePanelView.as_view(), name='ride'),
    path('panel/emergency', EmergencyPanelView.as_view(), name='emergency'),
    path('vale/', RideSearchView.as_view(), name='ride_search'),
    path('vale/<str:ride_code>', RideDetailView.as_view(), name='ride_detail'),
]

app_name = 'panel'

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("apps.ride.urls", namespace="panel")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # Swagger
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("api/mobile/", include("apps.ride.api.mobile.urls"), name='mobile'),
    path("api/fleet/", include("apps.ride.api.fleet.urls", namespace='api_fleet_panel'), name='api_fleet_panel'),
    path("api/company/", include("apps.ride.api.company.urls", namespace='api_company_panel'), name='api_company_panel'),
    path("api/driver/", include("apps.ride.api.driver.urls", namespace='api_driver_panel'), name='api_driver_panel'),
    path("api/ride/", include("apps.ride.api.ride.urls", namespace='api_ride_panel'), name='api_ride_panel'),
    path("api/programming/", include("apps.ride.api.programming.urls", namespace='api_programming_panel'), name='api_programming_panel'),
    path("api/emergency/", include("apps.ride.api.emergency.urls", namespace='api_emergency_panel'), name='api_emergency_panel'),
    # Django-rq
    path('django-rq/', include('django_rq.urls'))
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/ride/api/company/views.py
from apps.common.views import NoPatchView
from apps.ride.models import Company
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView

from .serializers import CompanySerializer


class CompanyCreateListAPIView(ListCreateAPIView):
    queryset = Company.objects.all().select_related('address').order_by('id')
    serializer_class = CompanySerializer


class CompanyRetrieveUpdateDestroyAPIView(NoPatchView, RetrieveUpdateDestroyAPIView):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer

apps/ride/api/driver/views.py
from apps.common.views import NoPatchView
from django.contrib.auth.models import Group
from apps.users.models import User
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView

from .serializers import DriverSerializer


class DriverCreateListAPIView(ListCreateAPIView):
    queryset = User.objects.filter(groups__name='driver').select_related('car').order_by('id')
    serializer_class = DriverSerializer


class DriverRetrieveUpdateDestroyAPIView(NoPatchView, RetrieveUpdateDestroyAPIView):
    queryset = User.objects.filter(groups__name='driver').select_related('car')
    serializer_class = DriverSerializer

apps/ride/api/emergency/views.py
from apps.common.constants import ASK_HELP, EMERGENCY
from apps.ride.models import Drift
from rest_framework.generics import ListAPIView, UpdateAPIView

from .serializers import EmergencyListSerializer, EmergencyUpdateSerializer


class EmergencyListAPIView(ListAPIView):
    queryset = Drift.objects.filter(status__in=[EMERGENCY, ASK_HELP], operator_status__isnull=True).prefetch_related('ride', 'ride__driver', 'ride__driver__car','passenger', 'pickup_photos', 'pickup_place')
    serializer_class = EmergencyListSerializer


class EmergencyUpdateAPIView(UpdateAPIView):
    queryset = Drift.objects.all()
    serializer_class = EmergencyUpdateSerializer

apps/ride/api/fleet/views.py
from apps.common.views import NoPatchView
from apps.ride.models import Car
from rest_framework.generics import (
    ListAPIView,
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)

from .serializers import CarBrandSerializer, CarModelSerializer, CarSerializer


class CarCreateListAPIView(ListCreateAPIView):
    queryset = Car.objects.all().order_by('id')
    serializer_class = CarSerializer


class CarRetrieveUpdateDestroyAPIView(NoPatchView, RetrieveUpdateDestroyAPIView):
    queryset = Car.objects.all()
    serializer_class = CarSerializer


class CarBrandListAPIView(ListAPIView):
    queryset = Car.objects.all()
    serializer_class = CarBrandSerializer


class CarModelListAPIView(ListAPIView):
    queryset = Car.objects.all()
    serializer_class = CarModelSerializer

apps/ride/api/mobile/views.py
from apps.common.filters import TimeStampDateFilter
from apps.common.views import EstandarPagination, NoPatchView
from apps.ride.models import Drift, Ride
from django_filters.rest_framework import DjangoFilterBackend, FilterSet, OrderingFilter
from rest_framework.generics import ListAPIView, RetrieveAPIView, UpdateAPIView

from .serializers import (
    ArrivalSerializer,
    DriverRideSerializer,
    EmergencySerializer,
    PickupSerializer,
    RideHistorySerializer,
    StartRideSerializer,
)


class DriverRideRetrieveAPIView(RetrieveAPIView):
    serializer_class = DriverRideSerializer

    def get_object(self):
        return self.request.user


class PickupUpdateAPIView(NoPatchView, UpdateAPIView):
    queryset = Drift.objects.all()
    serializer_class = PickupSerializer


class ArrivalUpdateAPIView(NoPatchView, UpdateAPIView):
    queryset = Ride.objects.all()
    serializer_class = ArrivalSerializer


class StartRideUpdateAPIView(NoPatchView, UpdateAPIView):
    queryset = Ride.objects.all()
    serializer_class = StartRideSerializer


class EmergencyUpdateAPIView(NoPatchView, UpdateAPIView):
    queryset = Drift.objects.all()
    serializer_class = EmergencySerializer


class HistoryFilter(FilterSet):
    start_arrival = TimeStampDateFilter(field_name='arrival_time', lookup_expr=('gt'))
    end_arrival = TimeStampDateFilter(field_name='arrival_time', lookup_expr=('lt'))
    order = OrderingFilter(
        fields=(
            ('arrival_time', 'arrival_time'),
            ('rate', 'rate'),
        ),
        field_labels={
            'arrival_time': 'Arrival time',
            'rate': 'Rate price',
        }
    )

    class Meta:
        model = Ride
        fields = []


class HistoryListAPIView(ListAPIView):
    serializer_class = RideHistorySerializer
    pagination_class = EstandarPagination
    filter_backends = [DjangoFilterBackend]
    filterset_class = HistoryFilter

    def get_queryset(self):
        return Ride.objects.filter(
            driver=self.request.user, finished_time__isnull=False
        ).prefetch_related('driver', 'car', 'arrival_place', 'drift_set', 'drift_set__pickup_place', 'drift_set__passenger')

apps/ride/api/programming/views.py
import django_rq
from apps.ride.models import Company, Programming, Ride
from apps.users.models import User
from rest_framework.generics import CreateAPIView, DestroyAPIView, UpdateAPIView
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializers import (
    DataDriftSerializer,
    DriverSerializer,
    ProgrammingUpdateSerializer,
    RideCreateSerializer,
    ShiftSerializer,
)
from .utils import finish_programming, generate_programing


class ShiftAPIView(APIView):
    def get(self, request, **kwargs):
        number = Programming.objects.filter(company_id=self.kwargs.get('id'), drift__isnull=False).distinct('drift__ride').count()
        qs_shifts = Programming.objects.filter(company=self.kwargs.get(
            'id'), drift__isnull=True).distinct('scheduled_time').order_by('scheduled_time')
        return Response({
            'programmed': number,
            'shifts': ShiftSerializer(qs_shifts, many=True).data
        }, status=200)


class DriverProgrammingDataAPIView(APIView):
    def get(self, request, **kwargs):
        programming = Programming.objects.get(id=self.kwargs.get('id'))
        company = programming.company
        scheduled_time = programming.scheduled_time
        qs_driver = User.objects.filter(groups__name='driver').select_related('car').exclude(
            id__in=User.objects.filter(
                rides_as_driver__scheduled_time=scheduled_time, groups__name='driver').values_list('id', flat=True))
        qs_drifts = Programming.objects.filter(
            drift__isnull=True,
            company_id=company.id,
            scheduled_time=scheduled_time
        ).order_by('ride_type', 'place__rate__code', 'place__distrito'
                   ).prefetch_related('place', 'place__distrito', 'place__rate', 'passenger')
        return Response({
            'drivers': DriverSerializer(qs_driver, many=True).data,
            'drifts': DataDriftSerializer(qs_drifts, many=True).data,
        }, status=200)


class RideCreateAPIView(CreateAPIView):
    queryset = Ride.objects.all()
    serializer_class = RideCreateSerializer


class ProgrammingUploadAPIView(APIView):
    parser_classes = [MultiPartParser]

    def put(self, request):
        excel_file = request.data['file']
        company = Company.objects.get(id=request.data['company_id'])
        django_rq.enqueue(generate_programing, excel_file, company)
        return Response({'message': 'processing'}, status=204)


class ProgrammingDestroyAPIView(DestroyAPIView):
    queryset = Programming.objects.all()


class ProgrammingUpdateAPIView(UpdateAPIView):
    queryset = Programming.objects.all()
    serializer_class = ProgrammingUpdateSerializer


class ProgrammingCleanAPIView(APIView):
    def get(self, request, **kwargs):
        Programming.objects.filter(company_id=self.kwargs.get('id'), drift__isnull=True).delete()
        return Response('Se limpió la programación', status=200)


class ProgrammingFinishAPIView(APIView):
    def get(self, request, **kwargs):
        django_rq.enqueue(finish_programming, self.kwargs.get('id'))
        return Response('Se limpió la programación', status=200)

apps/ride/api/ride/views.py
from apps.common.filters import TimeStampDateFilter
from apps.common.views import EstandarPagination, NoPatchView
from apps.ride.models import Drift, Rate, Ride
from django_filters import rest_framework as filters
from django_filters.rest_framework import DjangoFilterBackend, FilterSet
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveUpdateDestroyAPIView,
)

from .serializers import (
    DriftSerializer,
    RateSerializer,
    RideListSerializer,
    RideSerializer,
)


class RateListAPIView(ListAPIView):
    queryset = Rate.objects.all().order_by('id')
    serializer_class = RateSerializer


class RideFilter(FilterSet):
    scheduled_begin = TimeStampDateFilter(field_name='scheduled_time', lookup_expr=('gt'))
    scheduled_end = TimeStampDateFilter(field_name='scheduled_time', lookup_expr=('lt'))

    class Meta:
        model = Ride
        fields = ['driver', 'company']


class RideListAPIView(ListAPIView):
    queryset = Ride.objects.filter().prefetch_related('driver', 'driver__car', 'arrival_place').order_by('-created')
    serializer_class = RideListSerializer
    pagination_class = EstandarPagination
    filter_backends = [DjangoFilterBackend]
    filterset_class = RideFilter


class RideCreateAPIView(CreateAPIView):
    queryset = Ride.objects.all()
    serializer_class = RideSerializer


class RideRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Ride.objects.all()
    serializer_class = RideSerializer


class DriftCreateAPIView(CreateAPIView):
    queryset = Drift.objects.all()
    serializer_class = DriftSerializer


class DriftRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Drift.objects.all().prefetch_related('passenger')
    serializer_class = DriftSerializer

apps/templates/panel/company.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% csrf_token %}
<h1>Listado de Compañías</h1>
<button type="button" class="btn btn-primary mb-3" id="createBtnModal" >
  Agregar
</button> 
<div class="card">
    <div class="card-body table-responsive">
      <table class="table table-striped align-middle">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Dirección</th>
            <th scope="col">Referencia</th>
            <th scope="col">Correo</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody id="tableBody">
        </tbody>
      </table>
    </div>
</div>
{% endblock content %}

{% block modal %}
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="formModal" aria-hidden="true">
  <div class="modal-dialog  modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="formModalLabel">Compañía</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="formUpdate">
          <div class="form-outline mb-3">
            <input type="text" name="model" class="form-control" id="inputName"/>
            <label class="form-label" for="inputName">Nombre</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="plate" class="form-control" id="inputAddress"/>
            <label class="form-label" for="inputAddress">Dirección</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="capacity" class="form-control" id="inputReference" />
            <label class="form-label" for="inputReference">Referencia</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="capacity" class="form-control" id="inputEmail" />
            <label class="form-label" for="inputEmail">Correo</label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="btnSubmit" action="">Guardar</button>
      </div>
    </div>
  </div>
</div>
{% endblock modal %}

{% block javascript %}
    <script>
      const api ={
        company: {
          list:  "{% url 'api_company_panel:list_create' %}",
          create:  "{% url 'api_company_panel:list_create' %}",
          retrieve:  "{% url 'api_company_panel:retrieve_update_destroy' %}",
          update:  "{% url 'api_company_panel:retrieve_update_destroy' %}",
          delete:  "{% url 'api_company_panel:retrieve_update_destroy' %}",
        }
      }
    </script>
    <script src="{% static 'js/company/main.js' %}"></script>
{% endblock javascript %}

apps/templates/panel/emergency.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% csrf_token %}
<h1>Listado de recojos en emergencia</h1>
<div class="card">
    <div class="card-body table-reponsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Cod</th>
            <th scope="col">Conductor</th>
            <th scope="col">Pasajero</th>
            <th scope="col">Estado</th>
            <th scope="col">Distrito</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody id="tableBody">
        </tbody>
      </table>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
const api = {
    emergency: {
        update: "{% url 'api_emergency_panel:update' %}",
        list: "{% url 'api_emergency_panel:list' %}",
    }
}
</script>
<script src="{% static 'js/emergency/main.js' %}"></script>
{% endblock javascript %}

apps/templates/panel/programming.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% csrf_token %}
<div class="row my-3">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Programación</h2>
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col">
                            <select id ='companySelector' class="form-select" aria-label="Seleccionar empresa"></select>
                        </div>
                        <div class="col">
                           <button type="button" class="btn btn-primary" id="btnClean">Limpiar</button>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row hide" id="fileContainer">
                        <div class='col'>
                            <div class="form-file">
                              <input type="file" class="form-file-input" id="fileExcel">
                              <label class="form-file-label" for="customFile">
                                <span class="form-file-text" id="lblFileExcel">Selecciona un archivo...</span>
                                <span class="form-file-button">xls</span>
                              </label>
                            </div>
                        </div>
                        <div class="col">
                            <button type="button" class="btn btn-primary" id="btnUpdate">Subir</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" id="container-finish-programming">

</div>
<div class="row">
    <div id="shifts" class="col-3"></div>
    <div id="drivers" class="col-3"></div>
    <div id="drifts" class="col-6"></div>
</div>
<button type="button" class="btn btn-lg btn-success" id="btnRide">Crear Viaje</button>
{% endblock content %}

{% block modal %}
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="formModal" aria-hidden="true">
  <div class="modal-dialog  modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="formModalLabel">Detalle de programación</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="formUpdate">
          <div class="form-outline mb-3">
            <input type="text" name="firstName" class="form-control" disabled id="inputFirstName"/>
            <label class="form-label" for="firstName">Nombres</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="lastName" class="form-control" disabled id="inputLastName"/>
            <label class="form-label" for="lastName">Apellidos</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="address" class="form-control" id="inputAddress"/>
            <label class="form-label" for="address">Dirección</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="reference" class="form-control" id="inputReference"/>
            <label class="form-label" for="reference">Referencia</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="distrito" class="form-control" id="inputDistrito"/>
            <label class="form-label" for="rate">Distrito</label>
          </div>
          <div class="form-outline mb-3">
            <input type="text" name="rate" class="form-control" id="inputRate"/>
            <label class="form-label" for="rate">Codigo</label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="btnUpdateDrift" action="">Guardar</button>
      </div>
    </div>
  </div>
</div>
{% endblock modal %}


{% block javascript %}
<script>
const api = {
    company: {
        list: "{% url 'api_company_panel:list_create' %}",
    },
    programming: {
        file: "{% url 'api_programming_panel:file' %}",
        shift: "/api/programming/shift/",
        data: "{% url 'api_programming_panel:driver_drift' %}",
        ride: "{% url 'api_programming_panel:ride' %}",
        remove: "/api/programming/remove/",
        update: "/api/programming/update/",
        clean: "/api/programming/clean/",
        finish: "/api/programming/finish/"
    }
}
</script>
<script src="{% static 'js/programming/main.js' %}"></script>
{% endblock javascript %}